### ISSUE TITLE
Config not generating on version 0.4.1

### ISSUE THREAD

**Issue by breadguyyy** [MapleWheels/RoR2_QoLChanges#15] opened 2020-10-02 20:39 UTC
Using Windows 10, latest version
I also have the latest version of Bepinex, R2API, Bepinex Extensions, and QOL changes.
[LogOutput.log](https://github.com/MapleWheels/RoR2_QoLChanges/files/5320143/LogOutput.log)

**Comment by Undead-Tech** [comment] 2020-10-02 20:42
The plugin is not loading that's why, I just posted a report on this.

**Comment by breadguyyy** [comment] 2020-10-02 20:43
oh oops i didnt see your report, i was sent here from discord

**Comment by MapleWheels** [comment] 2020-10-02 20:44
Closed. Duplicate of #16 .

**Closed as completed by MapleWheels** 2020-10-02 20:44 UTC
